#!/bin/sh

/usr/bin/chromium %U --app="data:text/html,<html><body><script>window.moveTo(2604,94);window.resizeTo(286,517);window.location='https://www.adblockradio.com/player/';</script></body></html>"

